### ISSUE TITLE
Investigate meta build tool

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/model_builder#1]
Models will need to be built and tested with a range of supporting compiler toolchains, e.g. Intel Fortran+OpenMPI, gcc+OpenMPI, and libraries, e.g. netCDF, HDF, 

For this reason a meta-build tool is required, one which can control the environment in which a build takes place, specifying versions of all the software involved in a build.

Two possible candidates are [spack](https://spack.io) and [EasyBuild](https://easybuild.io).

Important criteria:

- [ ] Builds must be reproducible, possibly months or years later (though this will be bounded by HPC hardware changes)
- [ ] Builds must be uniquely identifiable: for provenance purposes a build "hash" or ID needs to be propagated from executables to experiments
- [ ] Build hashes/IDs must be unique enough to avoid clashes (redundant, covered by above?)
- [ ] Ability to utilise pre-built infrastructure libraries, specifically OpenMPI+Intel Fortran compiler

EasyBuild is designed with a "build everything" goal. Spack doesn't have this goal and has extensive support for specifying existing software packages to use in builds.

EasyBuild does not include the combination of Intel+OpenMPI in it's [common toolchains](https://docs.easybuild.io/en/latest/Common-toolchains.html) that are the most well supported and tested.

Spack creates `spack.lock` file with all details required to reproduce an environment:
- Versions
-  Compilers, compiler versions — Variant values
-  Optional dependencies
-  Target architecture

EasyBuild does not have such a focus on reproducibility because the architecture it isn't expected that old versions will deleted or changed, and with a design intended to build all components it doesn't have the same need to keep track of everything that was used in a build in the same way spack does.

For all these reasons spack is the meta build chosen to scope and test.

The initial scope/goals are:
1. Recreate COSIMA builds
2. Reproduce COSIMA model answers
3. Test building with different OpenMPI versions
4. Investigate sensitivity of model answer reproducibility to OpenMPI versions
5. Use same spec to build containerised environment (will require building more libraries)

Subsequent goals

1. Replace some system libraries with spack-built (netCDF, HDF5, ParallelIO)
2. Investigate sensitivity of model reproducibility to using spack built libraries

The initial goals are to recreate COSIMA builds and model answers. The logical way to do this is to use the same software to build the executables, i.e. match the compilers and libraries as closely as possible. Subsequently some of these system libraries can be replaced by spack built versions to investigate sensitivity of reproducibility.

**Comment by aekiss** [comment]
Investigation continued in https://forum.access-hive.org.au/t/initial-experiments-with-spack/90

Also see https://forum.access-hive.org.au/tag/spack
